version: '3'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: asdasd
      MYSQL_DATABASE: wyndham_script
      MYSQL_USER: root
      MYSQL_PASSWORD: asdasd
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
